<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Statistics', 'doctrine');

/**
 * BaseStatistics
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $hits
 * @property string $url
 * @property integer $portals_urls_id
 * @property PortalsUrls $PortalsUrls
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method integer     getHits()            Returns the current record's "hits" value
 * @method string      getUrl()             Returns the current record's "url" value
 * @method integer     getPortalsUrlsId()   Returns the current record's "portals_urls_id" value
 * @method PortalsUrls getPortalsUrls()     Returns the current record's "PortalsUrls" value
 * @method Statistics  setId()              Sets the current record's "id" value
 * @method Statistics  setHits()            Sets the current record's "hits" value
 * @method Statistics  setUrl()             Sets the current record's "url" value
 * @method Statistics  setPortalsUrlsId()   Sets the current record's "portals_urls_id" value
 * @method Statistics  setPortalsUrls()     Sets the current record's "PortalsUrls" value
 * 
 * @package    development
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatistics extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('statistics');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('hits', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('portals_urls_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PortalsUrls', array(
             'local' => 'portals_urls_id',
             'foreign' => 'id'));
    }
}