<?php

/**
 * PortalsUrlsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PortalsUrlsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PortalsUrlsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PortalsUrls');
    }
}