<?php

/**
 * StatisticsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatisticsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatisticsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Statistics');
    }
}