PortalsUrls:
  connection: doctrine
  tableName: portals_urls
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    url:
      type: string(255)
      unique: true
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Statistics:
      local: id
      foreign: portals_urls_id
      type: many
Statistics:
  connection: doctrine
  tableName: statistics
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    hits:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    url:
      type: string(255)
      unique: true
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    portals_urls_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    PortalsUrls:
      local: portals_urls_id
      foreign: id
      type: one